sonar.projectKey=kiennt1-hblab_tle-commerce
sonar.organization=kiennt1-hblab


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=tle-commerce
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.language=go
sonar.sourceEncoding=UTF-8